// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmfygtwwceeycllzaupv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZnlndHd3Y2VleWNsbHphdXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTM3MDYsImV4cCI6MjA3MjU4OTcwNn0.9gmJMfi3FvxE5vrdr2Bn6VK606pTPUR0kkT9O8dylfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});